# Generated by Django 3.1.1 on 2020-09-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
