# Generated by Django 3.1.1 on 2020-09-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200913_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
