# Generated by Django 3.1.1 on 2020-09-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200913_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postngo',
            name='user',
        ),
    ]
