# Generated by Django 3.1.1 on 2020-09-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200913_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postngo',
            name='date_created',
            field=models.DateField(),
        ),
    ]
