# Generated by Django 3.1.1 on 2020-09-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200913_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=200, null=True)),
                ('companyname', models.CharField(max_length=200, null=True)),
                ('manufacturing', models.DateField()),
                ('expiry', models.DateField()),
                ('tablets', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='postngo',
        ),
    ]
